package p001o;

/* renamed from: o.ژ */
public class C0281 {

    /* renamed from: ˊ */
    public static final String[] f1605 = { "P201D", "Misfire Harmful To catalytic converter/TWC(three way cat)",
            "P0522",
            "Diagnosis of tumble flap intake manifold open circuit of sensor lines tumble flap shafts stick in nonactuated position" };

    /* renamed from: ˋ */
    public static final String[] f1606 = { "P1103", "Turbocharger Wastegate Actuator.", "P1104",
            "Turbocharger Wastegate Solenoid.", "P1105", "Fuel Pressure Solenoid.", "P1300",
            "Ignition Timing Adjustment circuit.", "P1400", "Manifold Differential Pressure Sensor circuit.", "P1500",
            "Alternator FR Terminal circuit.", "P1600", "Serial Communication Link.", "P1715",
            "Pulse Generator Assembly.", "P1750", "Solenoid Assembly.", "P1751", "A/T Control Relay.", "P1791",
            "Engine Coolant Temperature Level Input circuit.", "P1795", "Throttle Position Input circuit to TCM.",
            "B1000", "Inside temp.sensor performance", "B1001", "Inside temperature sensor low", "B1002",
            "Inside temperature sensor high", "B1003", "Inside temperature sensor open", "B1004",
            "Inside temperature SNSR.inactive", "B1005", "Rear inside TEMP.SNS.performance", "B1006",
            "Rear inside TEMP. sensor low", "B1007", "Rear inside TEMP. sensor high", "B1008",
            "Rear inside TEMP. sensor open", "B1009", "Rear inside TEMP.sensor inactive", "B1010",
            "Outside temp. sensor performance", "B1011", "Outside temperature sensor low", "B1012",
            "Outside temperature sensor high", "B1013", "Outside temperature sensor open", "B1014",
            "Outside TEMP. sensor inactive", "B1015", "Heater water TEMP.S.performance", "B1016",
            "Heater water TEMP. sensor low", "B1017", "Heater water TEMP. sensor high", "B1018",
            "Heater water TEMP. sensor open", "B1019", "Heater water TEMP. SNSR.inactive", "B1020",
            "Air thermo sensor performance", "B1021", "Air thermo sensor low", "B1022", "Air thermo sensor high",
            "B1023", "Air thermo sensor open", "B1024", "Air thermo sensor inactive", "B1025",
            "Rear air thermo SNSR.performance", "B1026", "Rear air thermo sensor low", "B1027",
            "Rear air thermo sensor high", "B1028", "Rear air thermo sensor open", "B1029",
            "Rear air thermo sensor inactive", "B1030", "Pressure sensor performance", "B1031", "Pressure sensor high",
            "B1032", "Pressure sensor low", "B1033", "Pressure sensor open", "B1034", "Pressure sensor inactive",
            "B1035", "R.control TEMP. performance", "B1036", "R.control temperature high", "B1037",
            "R.control temperature low", "B1038", "R.control temperature open", "B1039",
            "R.control temperature inactive", "B1040", "A/M damper potentio. performance", "B1041",
            "A/M damper potentiometer high", "B1042", "A/M damper potentiometer low", "B1043",
            "A/M damper potentiometer open", "B1044", "A/M damper potentio. inactive", "B1045", "Air mix damper motor",
            "B1046", "A/M DMPR.travel range too small", "B1047", "A/M DMPR.travel range too large", "B1050",
            "R.A/M DMPR.potentio.performance", "B1051", "R.A/M damper potentiometer high", "B1052",
            "R.A/M damper potentiometer low", "B1053", "R.A/M damper potentiometer open", "B1054",
            "R.A/M damper potentio.inactive", "B1055", "Rear air mix damper motor", "B1056",
            "R.A/M damper travel too small", "B1057", "R.A/M damper travel too large", "B1060",
            "Air outlet potentio.performance", "B1061", "Air outlet damper potentio.high", "B1062",
            "Air outlet damper potentio.low", "B1063", "Air outlet damper potentio.open", "B1064",
            "Air outlet potentio.Inactive", "B1065", "Air outlet changeover DMPR.motor", "B1066",
            "Air outlet travel range too S", "B1067", "Air outlet travel range too L", "B1070",
            "R.air outlet potenti.performance", "B1071", "R.air outlet DMPR.potentio.high", "B1072",
            "R.air outlet DMPR.potentio.low", "B1073", "R.air outlet DMPR.potentio.open", "B1074",
            "R.air outlet potentio.Inactive", "B1075", "R.air outlet changeover DMPR.MTR", "B1076",
            "R.air outlet travel too small", "B1077", "R.air outlet travel too large", "B1080",
            "Rear solenoid valve relay", "B1081", "Control panel comm.error", "B1082", "AUTO/MANUAL data problem",
            "B1083", "EEPROM error", "B1084", "R.Def.output circuit OPN/SHT GND", "B1085",
            "R.Def.output circuit short 12V", "B1086", "Recirc output circuit low(short)", "B1087",
            "Recirc output circuit high(open)", "B1088", "A/M DMPR.motor driver (short)", "B1089",
            "A/M DMPR.motor driver (open)", "B1090", "A/M DMPR.motor blocked (left)", "B1091",
            "A/M DMPR.motor blocked (right)", "B1092", "Signal (brower fan On) failure", "B1093",
            "Sun sensor circuit low", "B1094", "PTC heater Comm./Not equipped", "B1095", "PTC heater1 open", "B1096",
            "PTC heater1 short", "B1097", "PTC heater2 open", "B1098", "PTC heater2 short", "B1099", "PTC heater3 open",
            "B1100", "PTC heater3 short", "B1200", "Odometer failure", "B1201", "Fuel information problem", "B1202",
            "Meter ECU power supply problem", "B1203", "The sticking of ODO/Trip switch", "B1300", "Topstack switch",
            "B1301", "5bow sensor:Up&Down=ON", "B1302", "5bow sensor:L=ON/R=OFF", "B1303", "5bow sensor:L=OFF/R=ON",
            "B1304", "Topstack POS.sensor:Up&Down=ON", "B1305", "TN panel close sensor:L=ON/R=OFF", "B1306",
            "TN panel close sensor:L=OFF/R=ON", "B1307", "TN latch close sensor:L=ON/R=OFF", "B1308",
            "TN latch close sensor:L=OFF/R=ON", "B1309", "Timeout error (5bow up)", "B1310",
            "Timeout error (TN latch open)", "B1311", "TN panel sensor:Close&Open=ON", "B1312",
            "Timeout error (TN panel open)", "B1313", "Timeout error (Topstack down)", "B1314",
            "Timeout error (TN panel close)", "B1315", "Timeout error (TN latch close)", "B1316",
            "Timeout error (Topstack up)", "B1317", "Timeout error (5bow down)", "B1318", "Valve actuation", "B1319",
            "Pump motor protection timeout", "B1320", "Quarter window cancel current", "B1321",
            "Comm.error (DR P/W ECU)", "B1322", "Comm.error (AS P/W ECU)", "B1323", "IG1 SW input", "B1324",
            "Driver side \u001f\u001fP/W ECU", "B1325", "Assist side P/W ECU", "B1326", "TN latch sensor:Close&Open=ON",
            "B1340", "EEPROM error", "B1400", "F ABG(1)DR.squib short", "B1401", "F ABG(1)DR.squib open", "B1402",
            "F ABG(1)DR.squib grounding", "B1403", "F ABG(1)DR.squib short to BATT.", "B1404",
            "F ABG(1)DR.active circuit short", "B1405", "F ABG(1)DR active circuit open", "B1406",
            "FR analog G sensor fail", "B1407", "FR impact sensor low voltage", "B1408", "FR impact sensor faulty COM.",
            "B1409", "FR impact sensor No COM.", "B1410", "F ABG(1)PS.squib short", "B1411", "F ABG(1)PS.squib open",
            "B1412", "F ABG(1)PS.squib grounding", "B1413", "F ABG(1)PS.squib short to BATT.", "B1414",
            "F ABG(1)PS.active circuit short", "B1415", "F ABG(1)PS active circuit open", "B1416",
            "FL analog G sensor fail", "B1417", "FL impact sensor low voltage", "B1418", "FL impact sensor faulty COM.",
            "B1419", "FL impact sensor No COM.", "B1420", "FR side ABG squib short", "B1421", "FR side ABG squib open",
            "B1422", "FR side ABG squib grounding", "B1423", "FR side ABG squib short to BAT.", "B1424",
            "FR side ABG active circuit short", "B1425", "FR side ABG active circuit open", "B1426",
            "FR side analog G sensor fail", "B1427", "FR side impact sensor low VOLT.", "B1428",
            "FR side impact sensor faulty COM", "B1429", "FR side impact sensor No COM.", "B1430",
            "FL side ABG squib short", "B1431", "FL side ABG squib open", "B1432", "FL side ABG squib grounding",
            "B1433", "FL side ABG squib short to BATT", "B1434", "FL side ABG active circuit short", "B1435",
            "FL side ABG active circuit open", "B1436", "FL side analog G sensor fail", "B1437",
            "FL side impact sensor low VOLT.", "B1438", "FL side impact sensor faulty COM", "B1439",
            "FL side impact sensor No COM.", "B1440", "FR curtain ABG squib short", "B1441",
            "FR curtain ABG squib open", "B1442", "FR curtain ABG squib grounding", "B1443",
            "FR curtain ABG squib SHT.to BAT", "B1444", "FR curtain ABG active circuit SH", "B1445",
            "FR curtain ABG active circuit OP", "B1446", "RR side analog G sensor fail", "B1447",
            "RR side impact SNS.low voltage", "B1448", "RR side impact SNS.faulty COM.", "B1449",
            "RR side impact SNS.No COM.", "B1450", "FL curtain ABG squib short", "B1451", "FL curtain ABG squib open",
            "B1452", "FL curtain ABG squib grounding", "B1453", "FL curtain ABG squib SHT.to BAT", "B1454",
            "FL curtain ABG active circuit SH", "B1455", "FL curtain ABG active circuit OP", "B1456",
            "RL side analog G sensor fail", "B1457", "RL side impact sensor low VOLT.", "B1458",
            "RL side impact sensor faulty COM", "B1459", "RL side impact sensor No COM.", "B1460",
            "FR pretensioner squib short", "B1461", "FR pretensioner squib open", "B1462",
            "FR pretensioner squib grounding", "B1463", "FR pretensioner squib SHT.to BAT", "B1464",
            "FR preten.active circuit short", "B1465", "FR preten.active circuit open", "B1466",
            "Front ABG analog G sensor fail", "B1467", "Front ABG safing G sensor open", "B1468",
            "Front ABG safing G sensor short", "B1469", "Side ABG safing G sensor fail", "B1470",
            "FL pretensioner squib short", "B1471", "FL pretensioner squib open", "B1472",
            "FL pretensioner squib grounding", "B1473", "FL pretensioner squib SHT.to BAT", "B1474",
            "FL preten.active circuit short", "B1475", "FL preten.active circuit open", "B1476",
            "IG1(A) voltage extradinary low", "B1477", "IG1(B) voltage extradinary low", "B1478",
            "B/U capacitor terminal high VOLT", "B1479", "B/U Capacitor terminal low VOLT.", "B1480",
            "F ABG(2)DR squib short", "B1481", "F ABG(2)DR squib open", "B1482", "F ABG(2)DR squib grounding", "B1483",
            "F ABG(2)DR squib short to BATT.", "B1484", "F ABG(2)DR active circuit short", "B1485",
            "F ABG(2)DR active circuit open", "B1486", "Seatbelt alarm lamp circuit Fail", "B1487",
            "Seatbelt alarm lamp harness open", "B1488", "OFF alarm lamp circuit fail", "B1489",
            "OFF alarm lamp circuit open", "B1490", "F ABG(2)PS squib short", "B1491", "F ABG(2)PS squib open", "B1492",
            "F ABG(2)PS squib grounding", "B1493", "F ABG(2)PS squib short to BATT.", "B1494",
            "F ABG(2)PS active circuit short", "B1495", "F ABG(2)PS active circuit open", "B1496", "Control unit",
            "B1497", "EEPROM", "B1498", "Control unit", "B1499", "Control unit collision decision", "B1500",
            "RR curtain ABG squib short", "B1501", "RR curtain ABG squib open", "B1502",
            "RR curtain ABG squib grounding", "B1503", "RR curtain ABG squib SHT.to BAT", "B1504",
            "RR curtain ABG active circuit SH", "B1505", "RR curtain ABG active circuit OP", "B1506",
            "DR.seat position SW open", "B1507", "DR.seat position SW short to GND", "B1508",
            "DR.seat position SW short to BAT", "B1509", "Wrong installation of ECU", "B1510",
            "RL curtain ABG squib short", "B1511", "RL curtain ABG squib open", "B1512",
            "RL curtain ABG squib grounding", "B1513", "RL curtain ABG squib SHT.to BAT", "B1514",
            "RL curtain ABG active circuit SH", "B1515", "RL curtain ABG active circuit OP", "B1516",
            "PS.seat position SW open", "B1517", "PS.seat position SW short to GND", "B1518",
            "PS.seat position SW short to BAT", "B1519", "Connector lock", "B1520", "DR.buckle SW fault", "B1521",
            "DR.buckle SW open for N.C", "B1522", "DR.buckle SW SHT.to GND for N.C", "B1523",
            "DR.buckle SW SHT.to BATT.for N.C", "B1524", "DR.buckle SW open for N.C", "B1525",
            "DR.buckle SW SHT.to GND for N.O", "B1526", "DR.buckle SW SHT.to BATT.for N.O", "B1527",
            "DR.buckle SW OPEN for COM", "B1528", "DR.buckle SW SHT.to GND for COM", "B1529",
            "DR.buckle SW SHT.to BATT.for COM", "B1530", "PS.buckle SW fault", "B1531", "PS.buckle SW open for N.C",
            "B1532", "PS.buckle SW SHT.to GND for N.C", "B1533", "PS.buckle SW SHT.to BATT.for N.C", "B1534",
            "PS.buckle SW open for N.C", "B1535", "PS.buckle SW SHT.to GND for N.O", "B1536",
            "PS.buckle SW SHT.to BATT.for N.O", "B1537", "PS.buckle SW OPEN for COM", "B1538",
            "PS.buckle SW SHT.to GND for COM", "B1539", "PS.buckle SW SHT.to BATT.for COM", "B1540",
            "OCSS control unit", "B1541", "OCSS calibration", "B1542", "OCSS sensor1", "B1543", "OCSS sensor2", "B1544",
            "OCSS seat belt sensor", "B1545", "OCSS control unit faulty Comm.", "B1546", "OCSS control unit No Comm.",
            "B1547", "Cut off for passenger's airbag", "B1548", "CAN No communication", "B1549",
            "CAN faulty communication", "B1550", "SRS alarm Lamp circuit fail", "B1551", "SRS alarm Lamp harness open",
            "B1552", "Change circuit for PWR.supply SH", "B1553", "Change circuit for PWR.supply OP", "B1554",
            "OCSS internal unit fail", "B1555", "OCSS internal unit circuit open", "B1556", "DR.seat position SW fail",
            "B1557", "Control unit", "B1558", "OCSS control unit", "B1559", "Cut off for driver front Airbag", "B1560",
            "DR.cut SW fault", "B1561", "DR.cut SW OPEN for N.C", "B1562", "DR.cut SW SHT.to GND for N.C", "B1563",
            "DR.cut SW SHT.to BATT.for N.C", "B1564", "DR.cut SW open for N.O", "B1565", "DR.cut SW SHT.to GND.for N.O",
            "B1566", "DR.cut SW SHT.to BATT.for N.O", "B1567", "DR.cut SW OPEN for COM", "B1568",
            "DR.cut SW SHT.to GND for COM", "B1569", "DR.cut SW SHT.to BATT.for COM", "B1570", "PS.cut SW fault",
            "B1571", "PS.cut SW OPEN for N.C", "B1572", "PS.cut SW SHT.to GND for N.C", "B1573",
            "PS.cut SW SHT.to BATT.for N.C", "B1574", "PS.cut SW open for N.O", "B1575", "PS.cut SW SHT.to GND.for N.O",
            "B1576", "PS.cut SW SHT.to BATT.for N.O", "B1577", "PS.cut SW OPEN for COM", "B1578",
            "PS.cut SW SHT.to GND for COM", "B1579", "PS.cut SW SHT.to BATT.for COM", "B1580",
            "DR.cut off SW wrong installation", "B1581", "PS.cut off SW wrong installation", "B1582",
            "FR impact sensor ID fault", "B1583", "FL impact sensor ID fault", "B1584",
            "FR side impact sensor ID fault", "B1585", "FL side impact sensor ID fault", "B1586",
            "RR side impact sensor ID fault", "B1587", "RL side impact sensor ID fault", "B1588",
            "B/UP capacitor up converter", "B1589", "B/UP capacitor down converter", "B1590",
            "B/UP capacitor capacitance big", "B1591", "B/UP capacitor capacitance small", "B1592",
            "Front analog G sensor failure", "B1593", "Front analog G SNS.noise fault", "B1594",
            "Control unit abnormal condition", "B1595", "FR impact sensor short", "B1596", "FR impact sensor open",
            "B1597", "FR impact sensor grounding", "B1598", "FR impact sensor short to BATT.", "B1599",
            "FL impact sensor short", "B1600", "FL impact sensor open", "B1601", "FL impact sensor grounding", "B1602",
            "FL impact sensor short to BATT.", "B1603", "DR pretensioner squib short", "B1604",
            "DR pretensioner squib open", "B1605", "DR pretensioner squib grounding", "B1606",
            "DR pretensioner squib SHT.to BAT", "B1607", "DR preten.active circuit short", "B1608",
            "DR preten.active circuit open", "B1609", "PS pretensioner squib short", "B1610",
            "PS pretensioner squib open", "B1611", "PS pretensioner squib grounding", "B1612",
            "PS pretensioner squib SHT.to BAT", "B1613", "PS preten.active circuit short", "B1614",
            "PS preten.active circuit open", "B1615", "F ABG electronic safing SNS.fail", "B1616",
            "F ABG safing G sensor fail", "B1617", "Roll rate sensor failure", "B1618", "Z axis low G Sensor failure",
            "B1699", "Collective deployment", "B1700", "Odometer data fail", "B1701", "Intermittent wiper data fail",
            "B1702", "Transponder read error", "B1703", "Transponder ID unmatched", "B1704", "Auto light sensor open",
            "B1705", "Auto light sensor short", "B1706", "Flasher fuse blown", "B1707", "Flasher open", "B1708",
            "Front wiper intermittent", "B1709", "ETACS ECU(EEPROM)", "B1710", "ETACS ECU(ROM)", "B1711",
            "ETACS ECU(RAM)", "B1712", "Rain sensor fail", "B1713", "Rain auto light sensor fail", "B1714",
            "Auto light sensor fail", "B1720", "Key battery low", "B1721", "Immobilizer-basestation fail", "B1722",
            "Immobilizer-antenna fail", "B1723", "Immob-transponder comm.fail", "B1724",
            "Mode byte failure in CAN message", "B1725", "Immobilizer-CAN massage fail", "B1726",
            "Immob-too much challenge receive", "B1727", "Supply voltage", "B1728", "Supply voltage(undervoltage)",
            "B1729", "Supply voltage(overvoltage)", "B1730", "Immob-transponder comm.fail", "B1731",
            "Engine ECU communication timeout", "B1740", "Turn signal(RH) bulb outage", "B1741",
            "Turn signal(LH) bulb outage", "B1742", "Turn signal switch fail", "B1743", "Hazard lamp fuse blowing out",
            "B1744", "Hazard button fail", "B1750", "Driver's door status fail", "B1751", "Driver's door(lock)",
            "B1752", "Driver's door(unlock)", "B1753", "Driver's door(deadunlock)", "B1760", "Coding data mismatch",
            "B1761", "Chassis No. not programmed", "B1762", "IOD fuse not seated fully", "B1763", "Lighting switch",
            "B1764", "Wiper switch", "B1765", "ECU fuse", "B1766", "Already learned by other vehicle", "B1767",
            "CAN/LIN/SWS converter internal", "B1900", "Rheostat line open", "B1901", "Communication error of compass",
            "B2400", "KOS key registration fail", "B2401", "KOS key ID not registered", "B2402",
            "STL.unit comm.(system ID)", "B2403", "STL.unit comm.(CRC)", "B2404", "STL.unit comm.(function code)",
            "B2405", "STL.unit comm.(rolling code)", "B2406", "STL.unit comm.(PTC operate)", "B2407",
            "STL.unit comm.(EEPROM)", "B2408", "STL.unit comm.(solenoid)", "B2409", "STL.unit comm.(No response)",
            "B2410", "Rear antenna(indoor) open", "B2411", "Lock/unlock SW fail", "B2412", "LF antenna power voltage",
            "B2413", "STL.unit power voltage", "B2414", "Unlock sensor fail", "B2415", "RA module power voltage",
            "B2416", "ECU internal error", "B2801", "Power voltage too high", "B2802", "Power voltage too low", "B2811",
            "Logic voltage too high", "B2812", "Logic voltage too low", "B2821", "Pump motor TEMP.SNSR:SHT to BAT",
            "B2824", "Pump motor TEMP.SNSR:SHT to GND", "B2831", "ECU internal (RAM)", "B2832", "ECU internal (ROM)",
            "B2833", "ECU internal (TEMP. protection)", "B2834", "ECU internal (reference voltage)", "B2835",
            "ECU internal (EEPROM)", "B2836", "ECU internal (watchdog)", "B2837", "ECU internal (general error)",
            "B2841", "Hall sensor power:SHT to BAT", "B2842", "Hall sensor power:SHT to GND", "B2854",
            "Side latch hall sensor:no signal", "B2861", "PWR.striker hall SNS:SHT to BAT", "B2862",
            "PWR.striker hall SNS:SHT to GND", "B2863", "PWR.striker hall SNS:no signal", "B2864",
            "PWR.striker hall SNS:SHT to GND", "B2871", "Pump motor:short to battery", "B2872",
            "Pump motor:short to ground", "B2874", "Pump motor:open line", "B2875", "Pump motor:over current", "B2877",
            "Pump motor:low current", "B2878", "Pump motor:not connected", "B2881", "R.center latch motor:SHT to BAT",
            "B2882", "R.center latch motor:SHT to GND", "B2884", "R.center latch motor:open line", "B2887",
            "R.center latch motor:overheated", "B2891", "PWR.striker motor:short to BAT", "B2892",
            "PWR.striker motor:short to GND", "B2893", "PWR.striker motor:unexpect block", "B2895",
            "PWR.striker motor:over current", "B2898", "PWR.striker motor:not connected", "B2902",
            "Buzzer output:short to ground", "B2911", "F/B trunk status output:SHT-BAT", "B2912",
            "F/B trunk status output:SHT-GND", "B2921", "PWR.striker retracted:SHT-BAT", "B2924",
            "PWR.striker retracted:open line", "B2926", "PWR.striker retract:open T/out", "B2927",
            "PWR.striker retract:open T/out", "B2928", "PWR.striker retract:close T/out", "B2929",
            "PWR.striker retract:close T/out", "B2931", "Down latch LH open:short to BAT", "B2934",
            "Down latch LH open:open line", "B2936", "Down latch LH open:open timeout", "B2937",
            "Down latch LH open:open timeout", "B2938", "Down latch LH open:close timeout", "B2939",
            "Down latch LH open:close timeout", "B2941", "Down latch RH open:short to BAT", "B2944",
            "Down latch RH open:open line", "B2946", "Down latch RH open:open timeout", "B2947",
            "Down latch RH open:open timeout", "B2948", "Down latch RH open:close timeout", "B2949",
            "Down latch RH open:close timeout", "B2956", "Side latch LH open:open timeout", "B2957",
            "Side latch LH open:open timeout", "B2958", "Side latch LH open:close timeout", "B2959",
            "Side latch LH open:close timeout", "B2966", "Side latch RH open:open timeout", "B2967",
            "Side latch RH open:open timeout", "B2968", "Side latch RH open:close timeout", "B2969",
            "Side latch RH open:close timeout", "B2971", "Trunklid cylinder open:SHT-BAT", "B2974",
            "Trunklid cylinder open:open line", "B2976", "Trunklid cylinder open:OP T/out", "B2977",
            "Trunklid cylinder open:OP T/out", "B2978", "Trunklid cylinder open:CLS T/out", "B2979",
            "Trunklid cylinder open:CLS T/out", "B2981", "Trunklid cylinder close:SHT-BAT", "B2984",
            "Trunklid cylinder close:OPN.line", "B2986", "Trunklid cylinder close:OP T/out", "B2987",
            "Trunklid cylinder close:OP T/out", "B2988", "Trunklid cylinder close:CL T/out", "B2989",
            "Trunklid cylinder close:CL T/out", "B2991", "Main cylinder open:short to BAT", "B2994",
            "Main cylinder open:open line", "B2996", "Main cylinder open:open timeout", "B2997",
            "Main cylinder open:open timeout", "B2998", "Main cylinder open:close timeout", "B2999",
            "Main cylinder open:close timeout", "C1200", "FR wheel speed sensor", "C1201",
            "FR wheel speed sensor signal", "C1202", "FR wheel SPD.SNSR.power circuit", "C1205",
            "FL wheel speed sensor", "C1206", "FL wheel speed sensor signal", "C1207",
            "FL wheel SPD.SNSR.power circuit", "C1210", "RR wheel speed sensor", "C1211",
            "RR wheel speed sensor signal", "C1212", "RR wheel SPD.SNSR.power circuit", "C1215",
            "RL wheel speed sensor", "C1216", "RL wheel speed sensor signal", "C1217",
            "RL wheel SPD.SNSR.power circuit", "C1222", "Wheel SPD.SNSR.power circuit", "C1223",
            "Suspension of SNSR.active check", "C1225", "Deviation between wheel speed", "C1226", "FR inlet valve",
            "C1231", "FR outlet valve", "C1236", "FL inlet valve", "C1241", "FL outlet valve", "C1246",
            "RR inlet valve", "C1251", "RR outlet valve", "C1256", "RL inlet valve", "C1261", "RL outlet valve",
            "C1266", "Motor stuck", "C1271", "Motor drive circuit", "C1273", "Motor drive circuit stuck off", "C1274",
            "Motor drive circuit stuck on", "C1276", "Valve power supply circuit", "C1278",
            "Valve power circuit stuck off", "C1279", "Valve power circuit stuck on", "C1280", "Motor fail safe relay",
            "C1281", "Motor fail safe relay(stuck off)", "C1282", "Motor fail safe relay(stuck on)", "C1290",
            "Reverse signal", "C1291", "Reverse switch", "C1292", "Malfunction of network", "C1300", "FR cut valve",
            "C1305", "FR suction valve", "C1310", "FL cut valve", "C1315", "FL suction valve", "C1320",
            "Data length error(ENG)", "C1321", "Data length error(T/M)", "C1322", "Data length error(ETACS)", "C1330",
            "Mis-identification ENG.variation", "C1331", "Mis-identification T/M variation", "C1340",
            "Stop lamp switch", "C1341", "Brake stroke SNS.stuck/low gain", "C1342", "Brake stroke SNS.low voltage",
            "C1343", "Brake stroke SNS.high voltage", "C1345", "Brake fluid level insufficient", "C1350",
            "Rear inlet valve", "C1360", "INCOMP.learn neutral(M/C PRS.S)", "C1361", "M/C pressure SNSR.stuck/low gain",
            "C1362", "M/C pressure SNSR.low voltage", "C1363", "M/C pressure SNSR.high voltage", "C1364",
            "M/C pressure SNSR.malfunction", "C1365", "G sensor power supply", "C1366", "Lateral G SNSR.stuck/low gain",
            "C1367", "Lateral G SNSR.low voltage", "C1368", "Lateral G SNSR.high voltage", "C1371",
            "Yaw rate SNSR.stuck/low gain", "C1372", "Yaw rate SNSR.low voltage", "C1373", "Yaw rate SNSR.high voltage",
            "C1375", "Rear outlet valve", "C1377", "Comm.error G/Yaw rate sensor", "C1378",
            "Data length error(ASC sensor)", "C1379", "Data length error(STR.angle S.)", "C1381",
            "Straight G SNSR.stuck/low gain", "C1382", "Straight G SNSR.low voltage", "C1383",
            "Straight G SNSR.high voltage", "C1385", "Yaw rate sensor", "C1386", "Straight G sensor/G performance",
            "C1387", "Lateral G sensor/G performance", "C1388", "Yaw rate sensor active check", "C1389",
            "Straight G sensor active check", "C1390", "Lateral G sensor active check", "C1391",
            "INCOMP.learn neutral(Yawrate)", "C1392", "INCOMP.learn neutral(Straight G)", "C1393",
            "INCOMP.learn neutral(Lateral G)", "C1394", "INCOMP.learn neutral(SAS)", "C1395",
            "INCOMP.Brake fluid filling", "C1396", "Engine torque input refusal", "C1397",
            "T/M malfunction(Inhibitor SW)", "C1398", "Test mode", "C1399", "Drive test incomplete", "C1403",
            "Mode switch failure", "C1405", "Inappropriate tire diameter", "C1406", "Coupling protection operation",
            "C1408", "Actuator relay failure", "C1410", "Sol.abnormal current(initial)", "C1411",
            "Solenoid short circuit(initial)", "C1412", "Solenoid disconnection", "C1413", "Solenoid short circuit",
            "C1414", "Sol.abnormal current", "C1415", "Sol.abnormal current", "C1420", "IG SW start POS.circuit low",
            "C1421", "IG SW start POS.circuit high", "C1422", "Power supply high voltage", "C1423",
            "Power supply low voltage", "C1424", "ECU Internal/Sol. wiring error", "C1505", "Steering angle sensor",
            "C1506", "Steering angle sensor error", "C1511", "Torque sensor main", "C1512", "Torque sensor sub",
            "C1513", "Torque sensor main/sub voltage", "C1514", "Torque sensor power supply", "C1515",
            "Torque sensor amplifier circuit", "C1521", "Vehicle speed sensor", "C1522", "Crank angle sensor", "C1531",
            "Motor terminal voltage", "C1532", "Motor current too large", "C1533", "Motor over current", "C1534",
            "Motor current too small", "C1541", "Fail safe relay stuck ON", "C1542", "Fail safe relay stuck OFF",
            "C1551", "Hall-IC output voltage", "C1552", "Hall-IC output pattern", "C1553", "Optical sensor", "C1554",
            "Speed sensor is out of range", "C1555", "Steering angle SNS.out of range", "C1606", "RAM", "C1607",
            "ECU failure", "C1608", "EEPROM failure", "C1609", "ROM", "C1620", "ECU incorrect attachment", "C1621",
            "Yaw/G SNS.incorrect attachment", "C1640", "Coding not completed", "C1641", "Coding data mismatch", "C1860",
            "Power supply high voltage", "C1861", "Power supply low voltage", "C1862",
            "G/Yawrate power supply high VOLT", "C1863", "G/Yawrate power supply low VOLT.", "C1864",
            "G/Yawrate SNS.power supply VOLT.", "C1900", "Tire ID code No registration", "C1901",
            "Vehicle speed signal", "C1910", "Transmitter BATT.voltage,Tire1", "C1911", "Tire ID reception fail,Tire1",
            "C1912", "Tire air pressure low,Tire1", "C1913", "Acceleration sensor,Tire1", "C1914",
            "Tire air pressure sensor,Tire1", "C1915", "Transmitter OFF mode,Tire1", "C1920",
            "Transmitter BATT.voltage,Tire2", "C1921", "Tire ID reception fail,Tire2", "C1922",
            "Tire air pressure low,Tire2", "C1923", "Acceleration sensor,Tire2", "C1924",
            "Tire air pressure sensor,Tire2", "C1925", "Transmitter OFF mode,Tire2", "C1930",
            "Transmitter BATT.voltage,Tire3", "C1931", "Tire ID reception fail,Tire3", "C1932",
            "Tire air pressure low,Tire3", "C1933", "Acceleration sensor,Tire3", "C1934",
            "Tire air pressure sensor,Tire3", "C1935", "Transmitter OFF mode,Tire3", "C1940",
            "Transmitter BATT.voltage,Tire4", "C1941", "Tire ID reception fail,Tire4", "C1942",
            "Tire air pressure low,Tire4", "C1943", "Acceleration sensor,Tire4", "C1944",
            "Tire air pressure sensor,Tire4", "C1945", "Transmitter OFF mode,Tire4", "C1950",
            "Transmitter BATT.voltage,Tire5", "C1951", "Tire ID reception fail,Tire5", "C1952",
            "Tire air pressure low,Tire5", "C1953", "Acceleration sensor,Tire5", "C1954",
            "Tire air pressure sensor,Tire5", "C1955", "Transmitter OFF mode,Tire5", "P1010",
            "V.V.T. oil control valve", "P1012", "V.V.T. intake camshaft position", "P1020", "Oil control valve",
            "P1021", "Oil control Valve open", "P1022", "Oil control Valve 2", "P1023", "Oil control Valve 2 open",
            "P1025", "Oil control Valve open(Ex)", "P1027", "Oil control Valve 2 open(Ex)", "P1100",
            "Intake manifold tuning", "P1101", "TCL vacuum solenoid", "P1102", "TCL ventilation solenoid", "P1103",
            "Waste gate", "P1104", "Waste gate solenoid valve", "P1105", "Fuel pressure up solenoid", "P1120",
            "ETV magnet", "P1121", "ETV motor relay", "P1122", "ETV connector", "P1190", "Fuel pressure sensor 2",
            "P1200", "Injector drive", "P1201", "Injector drive 2", "P1203", "Injector charge problem(low)", "P1204",
            "Injector charge problem(over)", "P1210", "Intake throttle valve", "P1220", "ETV system", "P1221",
            "ETV motor feedback", "P1222", "ETV motor", "P1223", "ETV communication", "P1224", "ETV Motor 1", "P1225",
            "APS(sub)", "P1226", "ETV controller", "P1227", "Limp home solenoid", "P1228", "ETV motor 2", "P1230",
            "Fuel pump regulator", "P1231", "ASC data plausibility", "P1232", "Fail safe control", "P1233",
            "TPS(main) plausibility", "P1234", "TPS(sub) plausibility", "P1235", "AFS plausibility", "P1236",
            "A/D converter", "P1237", "APS plausibility", "P1238", "AFS plausibility(torque monitor)", "P1239",
            "Engine RPM plausibility", "P1240", "ASC retard request plausibility", "P1241", "Torque monitor", "P1242",
            "Fail safe control monitor", "P1243", "Engine ECU(microcomputer)", "P1244", "Engine ECU(RAM check)",
            "P1245", "Engine ECU(RAM check)", "P1246", "Engine ECU(LSI communication)", "P1272",
            "Pressure limiter malfunction", "P1273", "Supply pump insufficient flow", "P1274", "Supply pump protection",
            "P1275", "Supply pump exchange", "P1276", "Fuel filter exchange", "P1277", "Fuel filter freeze", "P1300",
            "IG timing adjustment terminal", "P1301", "IG timing adjustment signal", "P1313", "Lean surge", "P1320",
            "IG timing retard insufficient", "P1335", "Piston position sensor 1", "P1336", "Piston position sensor 2",
            "P1340", "Camshaft position sensor", "P1381", "Glow plug relay (+B short)", "P1382",
            "Glow plug relay (GND short)", "P1400", "MDP sensor", "P1403", "EGR valve 2", "P1427",
            "DPF temperature sensor low", "P1428", "DPF temperature sensor high", "P1443", "Purge control valve",
            "P1472", "DPF differential PRS.sensor low", "P1473", "DPF differential PRS.sensor high", "P1474",
            "TEMP.sensor(for DPF PRS.SNSR) LO", "P1475", "TEMP.sensor(for DPF PRS.SNSR) HI", "P1496",
            "Catalytic converter(high TEMP.)", "P1497", "DPF system", "P1498", "DPF over loading", "P1499",
            "DPF high temperature", "P1500", "Alternator field FR terminal", "P1506", "ISC rationality low", "P1507",
            "ISC rationality high", "P1513", "Remote control engine starter", "P1515", "Brake vacuum sensor", "P1530",
            "A/C switch chattering", "P1540", "Radiator sensor1 LIN comm.", "P1541", "Radiator sensor2 LIN comm.",
            "P1542", "Radiator sensor3 LIN comm.", "P1543", "DOR tampering monitor (A)", "P1544",
            "DOR tampering monitor (B)", "P1545", "DOR tampering monitor (C)", "P1546", "DOR tampering monitor (D)",
            "P1547", "DOR tampering monitor (E)", "P1560", "Current sensor 1", "P1561", "Current sensor 2", "P1562",
            "Engine room temperature sensor", "P1563", "Engine room temperature", "P1564", "Auto cruise switch",
            "P1571", "Stop lamp switch", "P1574", "ECU", "P1575", "Cancel latch", "P1580",
            "Encryption signal error for LIN", "P1601", "ECM-TVC ECU communication error", "P1602",
            "System LSI communication", "P1603", "Battery backup line", "P1604", "Chassis No. not programmed", "P1606",
            "EEPROM fail", "P1607", "Battery backup line system(T/M)", "P1608", "Battery current sensor circuit",
            "P1609", "Battery current sensor range", "P1610", "Immobilizer system", "P1615", "Starter fail safe relay",
            "P1620", "Injection pump (TPS)", "P1621", "Injection pump (TCV)", "P1622", "Injection pump (GE)", "P1623",
            "Injection pump (CSP sensor)", "P1624", "Injection pump (Q adjust ROM)", "P1625",
            "Injection Q.adjust valve", "P1626", "Injection Q.valve(not coding)", "P1705", "Shift actuator", "P1706",
            "Select switch", "P1715", "PG assy", "P1716", "PG assy", "P1720", "Vehicle speed sensor signal line",
            "P1730", "CVT system fail", "P1731", "CVT belt slip", "P1732", "Line pressure sensor open", "P1733",
            "Line pressure sensor short", "P1734", "Line pressure system fail(A)", "P1735",
            "Line pressure system fail(B)", "P1736", "Line pressure system fail(C)", "P1737",
            "Line pressure solenoid circuit", "P1738", "Primary speed sensor", "P1739", "Primary pressure sensor open",
            "P1740", "Primary pressure sensor short", "P1741", "CVT shift solenoid", "P1742", "CVT clutch solenoid",
            "P1743", "CVT clutch system fail(A)", "P1744", "CVT clutch system fail(B)", "P1745",
            "CVT-ABS communication line open", "P1746", "CVT cooler bypass valve open", "P1750", "Solenoid assy",
            "P1751", "A/T control relay", "P1753", "Solenoid1 assy", "P1758", "Solenoid2 assy", "P1760", "TPS short",
            "P1761", "TPS open", "P1762", "TPS fail", "P1763", "T/M fluid TEMP.SNSR.", "P1764",
            "T/M fluid TEMP.SNSR.short", "P1765", "Crank angle sensor open", "P1766", "Input shaft speed sensor",
            "P1767", "Output shaft speed sensor", "P1768", "K/D detent switch", "P1769", "Stop lamp switch", "P1770",
            "Inhibitor switch open", "P1771", "Inhibitor switch short", "P1772", "Vehicle speed sensor", "P1773",
            "LR/DIR solenoid", "P1774", "UD solenoid", "P1775", "2nd solenoid", "P1776", "OD solenoid", "P1777",
            "RED solenoid", "P1778", "DCC solenoid", "P1779", "Gear 1 incorrect ratio", "P1780",
            "Gear 2 incorrect ratio", "P1781", "Gear 3 incorrect ratio", "P1782", "Gear 4 incorrect ratio", "P1783",
            "Gear 5 incorrect ratio", "P1784", "Gear R incorrect ratio", "P1785", "Serial communication", "P1786",
            "DCC stuck OFF", "P1787", "DCC stuck ON", "P1788", "A/T control relay", "P1789", "N lamp", "P1790",
            "Battery backup line", "P1791", "ECT level input circuit", "P1792", "Front wheel speed sensor", "P1793",
            "Rear wheel speed sensor", "P1795", "Throttle position input", "P1807", "Transfer position sensor", "P1810",
            "F/W solenoid", "P1817", "Crank signal inhibition relay", "P1820", "Neutral switch 2", "P1830",
            "K/D servo SW open", "P1831", "K/D servo SW short", "P1832", "Shift solenoid 1 open", "P1833",
            "Shift solenoid 1 short", "P1834", "Shift solenoid 2 open", "P1835", "Shift solenoid 2 short", "P1836",
            "Pressure control valve open", "P1837", "Pressure control valve short", "P1838",
            "DCC/Lock up solenoid open", "P1839", "DCC/Lock up solenoid short", "P1840", "Shift solenoid GND to short",
            "P1841", "Torque reduction judgment 1", "P1842", "Torque reduction judgment 2", "P1843",
            "Shift solenoid 1 stuck ON", "P1844", "Shift solenoid 1 stuck OFF", "P1845", "Shift solenoid 2 stuck ON",
            "P1846", "Shift solenoid 2 stuck OFF", "P1847", "Lock up solenoid stuck ON", "P1848",
            "Lock up solenoid stuck OFF", "P1900", "AT ECU fail(Bus off)", "P1901", "A/T fail(Engine timeout)", "P1902",
            "A/T fail(Engine fail Info.)", "P2009", "Swirl control valve circuit low", "P2010",
            "Swirl control valve circuit high", "P2066", "Fuel level sensor(sub)", "P2096",
            "Post catalyst system too lean 1", "P2097", "Post catalyst system too rich 1", "P2098",
            "Post catalyst system too lean 2", "P2099", "Post catalyst system too rich 2", "P2100",
            "ETV motor circuit(open)", "P2101", "ETV motor magneto", "P2102", "ETV motor circuit(shorted low)", "P2103",
            "ETV motor circuit(shorted high)", "P2108", "ETV processor", "P2118", "Throttle actuator motor current",
            "P2119", "Throttle actuator throttle body", "P2121", "APS(main) range", "P2122", "APS(main) low", "P2123",
            "APS(main) high", "P2124", "APS(main) intermittent", "P2126", "APS(sub) range", "P2127", "APS(sub) low",
            "P2128", "APS(sub) high", "P2135", "TPS(main/sub) correlation", "P2138", "APS(main/sub) correlation",
            "P2146", "Injector common circuit1 open", "P2147", "Injector common circuit low", "P2148",
            "Injector common circuit high", "P2149", "Injector common circuit2 open", "P2173",
            "ETV control high air detected", "P2176", "ETV control without adaptation", "P2191",
            "System too lean at high load 1", "P2192", "System too rich at high load 1", "P2193",
            "System too lean at high load 2", "P2194", "System too rich at high load 2", "P2195",
            "Oxygen sensor(front) inactive", "P2197", "Oxygen sensor2(front) inactive", "P2226",
            "Barometric pressure sensor", "P2227", "Barometric pressure sensor range", "P2228",
            "Barometric pressure sensor low", "P2229", "Barometric pressure sensor high", "P2252",
            "O2S(front) negative current low", "P2253", "O2S(front) negative current high", "P2263",
            "Boost system monitor", "P2413", "EGR system performance", "P2454", "DPF differential PRS.sensor low",
            "P2455", "DPF differential PRS.sensor high", "P2567", "Radiator sensor thermistor error", "U1073",
            "Bus-Off", "U1100", "Engine CAN timeout", "U1101", "T/M CAN timeout/Not equipped", "U1102",
            "ASC/TCL/ABS timeout/Not equipped", "U1103", "PDC CAN timeout/Not equipped", "U1104",
            "SAS CAN timeout/Not equipped", "U1105", "YR/G CAN timeout/Not equipped", "U1106",
            "EPS CAN timeout/Not equipped", "U1107", "4WD CAN timeout/Not equipped", "U1108",
            "Meter CAN timeout/Not equipped", "U1109", "ETACS CAN timeout/Not equipped", "U1110",
            "A/C CAN timeout/Not equipped", "U1111", "Display CAN timeout/Not equipped", "U1112",
            "SRS-ABG CAN timeout/Not equipped", "U1113", "Display CAN timeout/Not equipped", "U1114",
            "TPMS CAN timeout/Not equipped", "U1116", "KOS CAN timeout/Not equipped", "U1117",
            "IMMOB.CAN timeout/Not equipped", "U1120", "Engine(CAN message)", "U1121", "T/M(CAN message)", "U1122",
            "ASC/TCL/ABS(CAN message)", "U1123", "PDC(CAN message)", "U1124", "SAS(CAN message)", "U1125",
            "Yaw rate/G sensor(CAN message)", "U1126", "EPS(CAN message)", "U1127", "4WD(CAN message)", "U1128",
            "Meter(CAN message)", "U1129", "ETACS(CAN message)", "U1130", "A/C(CAN message)", "U1131",
            "Display(CAN message)", "U1132", "SRS airbag(CAN message)", "U1133", "Display(CAN message)", "U1136",
            "KOS(CAN message)", "U1190", "No receive fault detect signal", "U1200", "SAS parity error", "U1201",
            "Yaw rate sensor parity error", "U1202", "Straight G sensor parity error", "U1203",
            "Lateral G sensor parity error", "U1204", "SAS message counter error", "U1205",
            "Yaw rate/G message counter error", "U1206", "Sleep instruction flag invalid", "U1300",
            "Data Length Error(ID:0E1)", "U1301", "Data Length Error(ID:0E3/0E4)", "U1302", "Data Length Error(ID:139)",
            "U1303", "Data Length Error(ID:13D)", "U1304", "Data Length Error(ID:14D)", "U1305",
            "Data Length Error(ID:152)", "U1306", "Data Length Error(ID:159)", "U1307", "Data Length Error(ID:16B)",
            "U1308", "Data Length Error(ID:16F)", "U1309", "Data Length Error(ID:1B1)", "U1310",
            "Data Length Error(ID:1B5)", "U1311", "Data Length Error(ID:1E1)", "U1312", "Data Length Error(ID:231)",
            "U1313", "Data Length Error(ID:232)", "U1314", "Data Length Error(ID:235)", "U1315",
            "Data Length Error(ID:239)", "U1316", "Data Length Error(ID:271)", "U1317", "Data Length Error(ID:2F1)",
            "U1318", "Data Length Error(ID:330)", "U1319", "Data Length Error(ID:331)", "U1320",
            "Data Length Error(ID:332)", "U1321", "Data Length Error(ID:333)", "U1322", "Data Length Error(ID:334)",
            "U1323", "Data Length Error(ID:335)", "U1324", "Data Length Error(ID:336)", "U1325",
            "Data Length Error(ID:337)", "U1326", "Data Length Error(ID:33D)", "U1327", "Data Length Error(ID:358)",
            "U1328", "Data Length Error(ID:423)", "U1329", "Data Length Error(ID:42F)", "U1330",
            "Data Length Error(ID:443)", "U1331", "Data Length Error(ID:445)", "U1332", "Data Length Error(ID:447)",
            "U1333", "Data Length Error(ID:570)", "U1334", "Data Length Error(ID:573)", "U1335",
            "Data Length Error(ID:584)", "U1336", "Data Length Error(ID:586)", "U1337", "Data Length Error(ID:587)",
            "U1338", "Data Length Error(ID:521)", "U1339", "Data Length Error(ID:100)", "U1340",
            "Data Length Error(ID:100)", "U1341", "Data Length Error(ID:300)", "U1400", "Data Error(ID:139)", "U1401",
            "Dynamic Range Error(ID:16B)", "U1402", "Dynamic Range Error(ID:16F)", "U1403",
            "Dynamic Range Error(ID:271)", "U1404", "Dynamic Range Error(ID:14D)", "U1405",
            "Dynamic Range Error(ID:14D/152)", "U1406", "Dynamic Range Error(ID:13D)", "U1407",
            "Dynamic Range Error(ID:231)", "U1408", "Dynamic Range Error(ID:235)", "U1409",
            "Dynamic Range Error(ID:235)", "U1410", "Dynamic Range Error(ID:235)", "U1411",
            "Dynamic Range Error(ID:235)", "U1412", "Dynamic Range Error(ID:E1)", "U1413", "Dynamic Range Error(ID:E1)",
            "U1414", "Dynamic Range Error(ID:E1)", "U1415", "Dynamic Range Error(ID:1B1)", "U1416",
            "Dynamic Range Error(ID:570)", "U1417", "Dynamic Range Error(ID:443)", "U1418",
            "Dynamic Range Error(ID:159)", "U1419", "Dynamic Range Error(ID:E4/E3)", "U1420",
            "Dynamic Range Error(ID:E4)", "U1421", "Dynamic Range Error(ID:E4/E3)", "U1422",
            "Dynamic Range Error(ID:2F1)", "U1423", "Dynamic Range Error(ID:570)", "U1424",
            "Dynamic Range Error(ID:570)", "U1425", "Dynamic Range Error(ID:570)", "U1426",
            "Dynamic Range Error(ID:573)", "U1427", "Dynamic Range Error(ID:573)", "U1428",
            "Dynamic Range Error(ID:423)", "U1429", "Dynamic Range Error(ID:423)", "U1430",
            "Dynamic Range Error(ID:445)", "U1431", "Dynamic Range Error(ID:445)", "U1432",
            "Dynamic Range Error(ID:445)", "U1433", "Data Error(ID:139)", "U1434", "Dynamic Range Error(ID:587)",
            "U1435", "Dynamic Range Error(ID:423)", "U1436", "Dynamic Range Error(ID:423)", "U1437",
            "Dynamic Range Error(ID:445)", "U1438", "Dynamic Range Error(ID:445)", "U1439",
            "Dynamic Range Error(ID:445)", "U1440", "Dynamic Range Error(ID:312)", "U1441",
            "Dynamic Range Error(ID:312)", "U1442", "Dynamic Range Error(ID:312)", "U1443",
            "Dynamic Range Error(ID:210)", "U1504", "Rain light LIN T.out/Not equip", "U1507",
            "LIN transmission error ETACS", "U1532", "LIN Rain autolight ECU", "U1570", "No bus activity error for LIN",
            "U1600", "MBUSY open", "U1601", "MBUSY short", "U1602", "MDATA open", "U1603", "MDATA short", "U1604",
            "MSCK open", "U1605", "MSCK short", "U1606", "M-BUS error", "U1700", "SWS communication line", "U1701",
            "Column SW SWS timeout", "U1702", "Front ECU SWS timeout", "U1703", "Sunroof CAN timeout/Not equipped",
            "U1704", "Dr.P/W SW SWS timeout/Not equip", "U1705", "Display SWS timeout/Not equipped", "U1706",
            "Corner SNS.SWS timeout/Not equip", "U1707", "Power gate SWS timeout/Not equip", "U1708",
            "ETACS SWS timeout", "B1000", "Inside temp.sensor performance", "B1001", "Inside temperature sensor low",
            "B1002", "Inside temperature sensor high", "B1003", "Inside temperature sensor open", "B1004",
            "Inside temperature SNSR.inactive", "B1005", "Rear inside TEMP.SNS.performance", "B1006",
            "Rear inside TEMP. sensor low", "B1007", "Rear inside TEMP. sensor high", "B1008",
            "Rear inside TEMP. sensor open", "B1009", "Rear inside TEMP.sensor inactive", "B1010",
            "Outside temp. sensor performance", "B1011", "Outside temperature sensor low", "B1012",
            "Outside temperature sensor high", "B1013", "Outside temperature sensor open", "B1014",
            "Outside TEMP. sensor inactive", "B1015", "Heater water TEMP.S.performance", "B1016",
            "Heater water TEMP. sensor low", "B1017", "Heater water TEMP. sensor high", "B1018",
            "Heater water TEMP. sensor open", "B1019", "Heater water TEMP. SNSR.inactive", "B1020",
            "Air thermo sensor performance", "B1021", "Air thermo sensor low", "B1022", "Air thermo sensor high",
            "B1023", "Air thermo sensor open", "B1024", "Air thermo sensor inactive", "B1025",
            "Rear air thermo SNSR.performance", "B1026", "Rear air thermo sensor low", "B1027",
            "Rear air thermo sensor high", "B1028", "Rear air thermo sensor open", "B1029",
            "Rear air thermo sensor inactive", "B1030", "Pressure sensor performance", "B1031", "Pressure sensor high",
            "B1032", "Pressure sensor low", "B1033", "Pressure sensor open", "B1034", "Pressure sensor inactive",
            "B1035", "R.control TEMP. performance", "B1036", "R.control temperature high", "B1037",
            "R.control temperature low", "B1038", "R.control temperature open", "B1039",
            "R.control temperature inactive", "B1040", "A/M damper potentio. performance", "B1041",
            "A/M damper potentiometer high", "B1042", "A/M damper potentiometer low", "B1043",
            "A/M damper potentiometer open", "B1044", "A/M damper potentio. inactive", "B1045", "Air mix damper motor",
            "B1046", "A/M DMPR.travel range too small", "B1047", "A/M DMPR.travel range too large", "B1050",
            "R.A/M DMPR.potentio.performance" };
}
